name: Rancher Flat Networking
description: |
  Rancher Networking plugin using Flat Networking.
version: v0.0.3
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
