version: '2'
services:
  flat:
    cap_add:
    - NET_ADMIN
    image: leodotcloud/swiss-army-knife:dev
    network_mode: flat
    # Force cni-driver to start first
    volumes_from:
    - cni-driver
    labels:
      io.rancher.sidekicks: cni-driver
      io.rancher.scheduler.global: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  cni-driver:
    privileged: true
    image: niusmallnan/net:flat
    command: sh -c "touch /var/log/rancher-cni.log && exec tail ---disable-inotify -F /var/log/rancher-cni.log"
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'rancher-bridge'
      io.rancher.container.dns: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
